[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
CoupledFields = "7ad07ef1-bdf2-5661-9d2b-286fd4296dac"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"


[compat]
Documenter = "~0.24"